chore: add docker compose configuration
ACM-Chapter-Cusco/kratos pull request #13
Opened 2024-09-05 17:25 UTC by anghelo-code

### Changes

Add Docker Compose configuration for two services:
- npm service: Installs all project dependencies using npm.
- frontend service: Runs the project in a development environment, making it easier to test and debug.

// Link the related issue to this pull request
Close #3

2024-09-05 18:48 UTC, Kleiber commented
We are going to create a new repository for the infrastructure so we can containerize our entire project. What do you think?

2024-09-05 19:37 UTC, anghelo-code commented
I like the idea

2024-09-06 01:24 UTC, Kleiber approved these changes

2024-09-06 01:24 UTC, Kleiber commented on docker/docker-compose.yml
> +    image: node:22-alpine3.19
Instead of using this image directly, could we have our own image where we contain our services?

2024-09-06 01:25 UTC, Kleiber requested changes

2024-09-06 01:25 UTC, Kleiber commented on docker/docker-compose.yml
> +    image: node:22-alpine3.19
Instead of using this image directly, could we have our own image where we contain our services?

2024-09-10 02:44 UTC, Kleiber commented
Not make sense for now since we will start to use google cloud services

2024-09-10 02:44 UTC, closed without merging